import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { I18nProvider } from "@/i18n/provider";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});


export const metadata: Metadata = {
  title: "Jordan Portfolio",
  description: "Generated by create next app",
  
};

const ppB = localFont({
  src: "../../assets/fonts/Poppins-Black.ttf",
  display: 'swap',
  variable: "--ppB"
})
const ppBold = localFont({
  src: "../../assets/fonts/Poppins-Bold.ttf",
  display: 'swap',
  variable: '--ppBold'
})
const ppEBold = localFont({
  src: "../../assets/fonts/Poppins-ExtraBold.ttf",
  display: 'swap',
  variable: "--ppEBold"
})
const ppELight = localFont({
  src: "../../assets/fonts/Poppins-ExtraLight.ttf",
  display: 'swap',
  variable: "--ppELight"
})
const ppLight = localFont({
  src: "../../assets/fonts/Poppins-Light.ttf",
  display: 'swap',
  variable: "--ppLight"
})
const ppMedium = localFont({
  src: "../../assets/fonts/Poppins-Medium.ttf",
  display: 'swap',
  variable: "--ppMedium"
})
const ppRegular = localFont({
  src: "../../assets/fonts/Poppins-Regular.ttf",
  display: 'swap',
  variable: "--ppRegular"
})
const ppSemiBold = localFont({
  src: "../../assets/fonts/Poppins-SemiBold.ttf",
  display: 'swap',
  variable: "--ppSemiBold"
})
const ppThin = localFont({
  src: "../../assets/fonts/Poppins-Thin.ttf",
  display: 'swap',
  variable: "--ppThin"
})


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`antialiased ${ppB.variable} ${ppBold.variable} ${ppThin.variable} ${ppSemiBold.variable} ${ppRegular.variable} ${ppMedium.variable} ${ppLight.variable}${ppELight.variable} ${ppEBold.variable}`}
      >
        <I18nProvider>
          {children}
        </I18nProvider>
      </body>
    </html>
  );
}
